-- Templates simplificados para NF enviada ao Financeiro/RH.
-- Mantem valores fora do corpo do e-mail; detalhes protegidos ficam no portal.

insert into comissionamento.notificacao_templates (
  codigo,
  versao,
  canal,
  assunto,
  titulo,
  corpo_html,
  corpo_texto,
  cta_label,
  cta_url_template,
  variaveis_obrigatorias,
  politica_mascaramento,
  ativo
) values
('secretaria_nf_recebida', 2, 'email',
 'Nota Fiscal recebida - Comissionamento {{ciclo}}',
 'Nota Fiscal recebida',
 '<p>Ola, {{nome_destinatario}}.</p><p>A Nota Fiscal do ciclo <strong>{{ciclo}}</strong> foi enviada por <strong>{{nf_enviada_por_nome}}</strong> e ficou registrada no portal.</p><p><strong>Numero:</strong> {{nf_numero}}<br><strong>Emissao:</strong> {{nf_data_emissao}}<br><strong>Arquivo:</strong> {{nf_nome_arquivo}}</p><p><strong>Observacao:</strong> {{nf_observacao}}</p><p>O fluxo ja seguiu para <strong>{{destino_pacote}}</strong>. Use o portal apenas para auditoria e acompanhamento.</p>',
 'Ola, {{nome_destinatario}}. NF recebida no ciclo {{ciclo}}. Enviada por {{nf_enviada_por_nome}} ({{nf_enviada_por_email}}). Numero: {{nf_numero}}. Emissao: {{nf_data_emissao}}. Arquivo: {{nf_nome_arquivo}}. Destino: {{destino_pacote}}. Portal: {{link_comissionamento}}',
 'Ver no portal',
 '{{link_comissionamento}}',
 array['ciclo','nome_destinatario','link_comissionamento','nf_enviada_por_nome','nf_enviada_por_email','nf_numero','nf_data_emissao','nf_nome_arquivo','nf_observacao','destino_pacote','correlation_id'],
 '{"ocultar_anexos": true, "ocultar_valor_comissionado": true, "ocultar_valor_nf": true}'::jsonb,
 true),
('financeiro_pacote_pj_enviado', 2, 'email',
 'Nota Fiscal enviada ao Financeiro - Comissionamento {{ciclo}}',
 'Nota Fiscal enviada ao Financeiro',
 '<p>Ola, {{nome_destinatario}}.</p><p>A Nota Fiscal de comissionamento PJ/autonomo do ciclo <strong>{{ciclo}}</strong> foi recebida e enviada ao <strong>{{destino_pacote}}</strong>.</p><p><strong>Enviada por:</strong> {{nf_enviada_por_nome}} ({{nf_enviada_por_email}})<br><strong>Numero da NF:</strong> {{nf_numero}}<br><strong>Data de emissao:</strong> {{nf_data_emissao}}<br><strong>Arquivo:</strong> {{nf_nome_arquivo}}</p><p><strong>Observacao:</strong> {{nf_observacao}}</p><p>Para consultar o documento protegido e dar andamento ao processamento, acesse o portal.</p>',
 'Ola, {{nome_destinatario}}. NF enviada ao Financeiro no ciclo {{ciclo}}. Enviada por {{nf_enviada_por_nome}} ({{nf_enviada_por_email}}). Numero: {{nf_numero}}. Emissao: {{nf_data_emissao}}. Arquivo: {{nf_nome_arquivo}}. Portal: {{link_comissionamento}}',
 'Abrir no portal',
 '{{link_comissionamento}}',
 array['ciclo','nome_destinatario','link_comissionamento','nf_enviada_por_nome','nf_enviada_por_email','nf_numero','nf_data_emissao','nf_nome_arquivo','nf_observacao','destino_pacote','status_usuario','proxima_acao','correlation_id'],
 '{"permitir_valor_pacote": false, "ocultar_anexos": true, "ocultar_valor_comissionado": true, "ocultar_valor_nf": true}'::jsonb,
 true),
('rh_financeiro_pacote_clt_enviado', 2, 'email',
 'Comissao CLT enviada para RH/Financeiro - {{ciclo}}',
 'Comissao CLT enviada para RH/Financeiro',
 '<p>Ola, {{nome_destinatario}}.</p><p>A comissao CLT do ciclo <strong>{{ciclo}}</strong> foi aprovada e enviada para <strong>{{destino_pacote}}</strong>.</p><p>Quantidade de itens: <strong>{{quantidade_itens}}</strong>.</p><p>Nota Fiscal nao se aplica a este perfil. Acompanhe os detalhes protegidos pelo portal.</p>',
 'Ola, {{nome_destinatario}}. Comissao CLT do ciclo {{ciclo}} enviada para {{destino_pacote}}. Itens: {{quantidade_itens}}. Portal: {{link_comissionamento}}',
 'Abrir no portal',
 '{{link_comissionamento}}',
 array['ciclo','nome_destinatario','link_comissionamento','quantidade_itens','destino_pacote','status_usuario','proxima_acao','correlation_id'],
 '{"permitir_valor_pacote": false, "ocultar_anexos": true, "ocultar_valor_comissionado": true}'::jsonb,
 true)
on conflict (codigo, versao, canal) do update set
  assunto = excluded.assunto,
  titulo = excluded.titulo,
  corpo_html = excluded.corpo_html,
  corpo_texto = excluded.corpo_texto,
  cta_label = excluded.cta_label,
  cta_url_template = excluded.cta_url_template,
  variaveis_obrigatorias = excluded.variaveis_obrigatorias,
  politica_mascaramento = excluded.politica_mascaramento,
  ativo = excluded.ativo;
